keybinding:
  universal:
    # should really be gg but this works
    gotoTop-alt: g
    gotoBottom-alt: G
    prevPage: "<c-u>"
    nextPage: "<c-d>"
    # scrollUpMain-alt2: '<c-b>'
    # scrollDownMain-alt2: '<c-f>' Keybindings
    scrollUpMain-alt1: <c-b>
    scrollDownMain-alt1: <c-f>
    # no need for it, swapped pgup with <c-u>
    scrollUpMain-alt2: <disabled>
    # no need for it, swapped pgdown with <c-d>
    scrollDownMain-alt2: <disabled>
  files:
    # frees up <c-f>
    findBaseCommitForFixup: <disabled>
    # frees up <c-b>
    openStatusFilter: <disabled>
  stash:
    # frees up g
    popStash: <disabled>
customCommands:
  - key: "<C-k>"
    context: "files"
    command: "lumen draft | tee >(pbcopy)"
    loadingText: "Generating message..."
    output: popup
  - key: "<C-l>"
    context: "files"
    command: "lumen draft -c {{.Form.Context | quote}} | tee >(pbcopy)"
    loadingText: "Generating message..."
    prompts:
      - type: "input"
        title: "Context"
        key: "Context"
    output: popup
