# If true, exit Lazygit when the user presses escape in a context where there is
# nothing to cancel/close
quitOnTopLevelReturn: true
git:
  pagers:
    # lazy git says delta --dark --paging=never
    #- pager: delta --paging=never
    - pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    - externalDiffCommand: difft --color=always
keybinding:
  universal:
    # should really be gg but this works
    gotoTop-alt: g
    gotoBottom-alt: G
    prevPage: "<c-u>"
    nextPage: "<c-d>"
    prevItem: "<up>"
    nextItem: "<down>"
    prevItem-alt: "<c-p>"
    nextItem-alt: "<c-n>"
    # these do not work fyi
    prevItem-alt2: k
    nextItem-alt2: j
    # scrollUpMain-alt2: '<c-b>'
    # scrollDownMain-alt2: '<c-f>' Keybindings
    scrollUpMain-alt1: <c-b>
    scrollDownMain-alt1: <c-f>
    # no need for it, swapped pgup with <c-u>
    scrollUpMain-alt2: <disabled>
    # no need for it, swapped pgdown with <c-d>
    scrollDownMain-alt2: <disabled>
  files:
    # frees up <c-f>
    findBaseCommitForFixup: <disabled>
    # frees up <c-b>
    openStatusFilter: <disabled>
  stash:
    # frees up g
    popStash: <disabled>
customCommands:
  - key: "<C-k>"
    context: "files"
    command: "lumen draft | tee >(pbcopy)"
    loadingText: "Generating message..."
    output: popup
  - key: "<C-l>"
    context: "files"
    command: "lumen draft -c {{.Form.Context | quote}} | tee >(pbcopy)"
    loadingText: "Generating message..."
    prompts:
      - type: "input"
        title: "Context"
        key: "Context"
    output: popup
